meta_product_name: "Contemporary Arts Society"
meta_title: "CAS - Contemporary Arts Society"
meta_description: "Championing art as a tool for change through engaging events and content to inspire and educate students on contemporary issues."
meta_image: "CASLOGO.png" # should exist in `app/assets/images/`
